### ISSUE TITLE
Todo list WebGUI

### ISSUE THREAD

**Issue by brantje** [chatnhook/chatnhook#21]
- [x] Add new projects
- [x] Save comm config
- [x] Save service config
- [x] Version numbering
- [x] Update button (upgrade to new Version)
- [x] System logging hook-bot.log

**Comment by brantje** [comment]
Fixed
